/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1a1c1f",
        "surface-container-highest": "#e2e2e6",
        "surface-container-low": "#f3f3f8",
        "surface-dim": "#d9dade",
        "tertiary-fixed-dim": "#f4bd6c",
        surface: "#f9f9fd",
        "surface-tint": "#32618f",
        "surface-container": "#ededf2",
        "on-tertiary-container": "#4f3300",
        "primary-fixed-dim": "#9dcafe",
        "on-tertiary-fixed": "#291800",
        "on-primary-fixed-variant": "#124976",
        "on-primary-fixed": "#001d35",
        outline: "#727780",
        "surface-container-lowest": "#ffffff",
        primary: "#32618f",
        "outline-variant": "#c2c7d0",
        "tertiary-fixed": "#ffddb2",
        "on-surface-variant": "#42474f",
        "surface-bright": "#f9f9fd",
        "inverse-on-surface": "#f0f0f5",
        "primary-container": "#79a6d8",
        background: "#f9f9fd",
        secondary: "#506073",
        "primary-fixed": "#d0e4ff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#d3e4fb",
        "error-container": "#ffdad6",
        "tertiary-container": "#cc994c",
        "on-secondary-fixed-variant": "#38485b",
        tertiary: "#7f560c",
        "secondary-fixed-dim": "#b7c8df",
        "surface-variant": "#e2e2e6",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#003b64",
        "on-primary": "#ffffff",
        "surface-container-high": "#e8e8ec",
        "on-tertiary-fixed-variant": "#624000",
        "secondary-container": "#d0e1f8",
        "on-error-container": "#93000a",
        "inverse-primary": "#9dcafe",
        "on-secondary-fixed": "#0b1d2d",
        "inverse-surface": "#2e3034",
        error: "#ba1a1a",
        "on-surface": "#1a1c1f",
        "on-error": "#ffffff",
        "on-secondary-container": "#546478",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        display: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
